version: '3.9'

services:
  bot:
    container_name: bot
    restart: always
    build: .
    command:
      - /bin/sh
      - -c
      - |
        ./run.sh
    env_file:
      - .env.vars
    depends_on:
      - mongodb
    networks:
      - bot-network

  mongodb:
    image: mongodb/mongodb-community-server:4.4-ubi8
    container_name: mongodb
     # environment:
     # MONGO_INITDB_ROOT_USERNAME: root
     # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - bot-network

volumes:
  mongo_data:

networks:
  bot-network:
    driver: bridge