version: '3.9'

services:
  bot:
    container_name: bot
    restart: always
    build: .
    command:
      - /bin/sh
      - -c
      - |
        ./run.sh
    env_file:
      - .env.vars
    volumes:
      - /etc/bot/db:./db/sqlite
      - /var/logs/bot:./logs
