version: '3.9'

services:
 
  web:
    build:
       context: ./web
       dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: parser_web
    command: >
        sh -c "python web/manage.py migrate
        && python web/manage.py runserver 0.0.0.0:8000
        && source web/app/create_superuser.sh"
    ports:
      - 7000:8000
    env_file:
      - .env
    environment:
      - DB_PATH=/app/sqlite
      - IMG_SERVER=http://213.171.14.158:8080/
      - TXT_SERVER=http://213.171.14.158:8070/
    networks:
      - parser
      
  img_proc:
    build:
       context: ./img_processor
       dockerfile: Dockerfile
    container_name: img_processor
    hostname: img
    ports:
      - 8080:8080
    volumes:
      - ./img_processor/images_new:/app/images_new
    networks:
      - parser
      
  txt_proc:
    build:
       context: ./text_processor
       dockerfile: Dockerfile
    container_name: text_processor
    hostname: txt
    ports:
      - 8070:8080
    networks:
      - parser
      
volumes:
  parser_logs:

networks:
  parser:
