"""referrer

Revision ID: 52bfbc8e70f0
Revises: f984f6591b25
Create Date: 2023-09-14 14:47:16.650631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bfbc8e70f0'
down_revision: Union[str, None] = 'f984f6591b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###
